### ISSUE TITLE
Add URL Shortner Guide

### ISSUE THREAD

**Issue by aminzabardast** [aminzabardast/dotfiles#106]
```yaml
services:
  shlink:
    container_name: shlink
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ="Europe/Istanbul"
      - DEFAULT_DOMAIN=amnz.me
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=mydbpassword
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 8089:8080

  database:
    container_name: shlink-db
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=mydbpassword
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=mydbpassword
    volumes:
      - ./db_data:/var/lib/mysql

  shlink-web-client:
    container_name: shlink-web-client
    image: shlinkio/shlink-web-client
    restart: always
    container_name: shlink-gui
    # volumes:
    #  - /home/docker/shlink/servers.json:/usr/share/nginx/html/servers.json
    depends_on:
      - shlink
    ports:
      - 8334:8080
```
