### ISSUE TITLE
Terminal Emulator on Web

### ISSUE THREAD

**Issue by aminzabardast** [aminzabardast/dotfiles#75]
A solution to access to the SSH of Workstation without terminal. Maybe a web terminal.

- Check this: https://github.com/paradoxxxzero/butterfly

**Comment by aminzabardast** [comment]
Betty is a better option: https://github.com/butlerx/wetty

**Comment by aminzabardast** [comment]
Using Wetty wit docker-compose:

The following works:
```yaml
services:
  wetty:
    image: wettyoss/wetty
    ports:
      - 3000:3000
    environment:
      SSHHOST: '10.14.23.4'
```

The following does not:
```yaml
services:
  wetty:
    image: wettyoss/wetty
    ports:
      - 3000:3000
    environment:
      SSHHOST: 'dell.amnz.me'
```

Something to do with the DNS and name resolving.

**Comment by aminzabardast** [comment]
Mapping the container network to the host networks solves the issue.

```yaml
services:
  wetty:
    image: wettyoss/wetty
    environment:
      SSHHOST: 'workstation.amnz.me'
    network: 'host'
```
